import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { CaptureGate } from "./components/CaptureGate";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { isCaptureMode, useCaptureBridge } from "./hooks/useCaptureBridge";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 *
 * The capture recorder (record-video.mjs) mirrors this exact formula for
 * silent / missing-audio steps so its schedule matches runtime behavior.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // Headless recording mode (?capture=1). Detected once at mount. The whole
  // presentation is driven externally through window.__capture (see
  // useCaptureBridge); no in-browser audio plays and all chrome is hidden.
  const [capture] = useState(isCaptureMode);
  const [captureStarted, setCaptureStarted] = useState(false);
  const captureArmed = capture && !captureStarted;

  // Auto mode shows a start gate until the user presses Space / clicks
  // (browsers block autoplay without a gesture). While it's up we (1) block
  // the stepper's nav keys so the SAME Space that releases auto-play doesn't
  // also advance past page 1, and (2) hold the scene unmounted so page 1's
  // entry animation plays in sync with its narration the moment playback
  // starts — instead of running, unwatched, behind the gate. Capture's black
  // pre-roll holds the scene the same way until __capture.start().
  const autoGateUp = mode === "auto" && !autoStarted;
  const sceneHidden = autoGateUp || captureArmed;

  const stepper = useStepper(CHAPTERS, sceneHidden);
  useCaptureBridge({
    enabled: capture,
    chapters: CHAPTERS,
    stepper,
    started: captureStarted,
    start: () => setCaptureStarted(true),
  });

  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  // Capture mode plays no audio in-browser (the recorder rebuilds the track).
  const audioSrc =
    capture || mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode: capture ? "manual" : mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next} capture={capture}>
        {!sceneHidden && (
          <div key={ch.id} className="scene">
            <Cmp step={stepper.cursor.step} />
          </div>
        )}
      </Stage>
      {!capture && (
        <>
          <ProgressBar
            chapters={CHAPTERS}
            cursor={stepper.cursor}
            onJumpChapter={stepper.jumpToChapter}
          />
          <AutoToggle mode={mode} onCycle={cycleMode} />
          <AutoStartGate
            visible={autoGateUp}
            onStart={() => setAutoStarted(true)}
          />
        </>
      )}
      <CaptureGate visible={captureArmed} />
    </>
  );
}
